version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - searxng_network  # ✅ Ensure Redis is on the correct network
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s
      start_period: 10s


  postgres:
    container_name: open-webui-postgres-1
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - searxng_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      retries: 5
      start_period: 10s

  searxng:
    container_name: open-webui-searxng-1
    image: searxng-custom
    restart: unless-stopped
    networks:
      - searxng_network
    ports:
      - "8888:8080"
    volumes:
      - /Users/robertlee/GitHubProjects/searxng-docker/searxng/settings.yml:/etc/searxng/settings.yml:rw
      - /Users/robertlee/GitHubProjects/searxng-docker/searxng/limiter.toml:/etc/searxng/limiter.toml:rw  # ✅ Ensure this is mapped
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      start_period: 10s



  openwebui:
    container_name: open-webui
    image: searxng/openweb-ui:latest
    restart: unless-stopped
    networks:
      - searxng_network
    ports:
      - "8081:80"
    volumes:
      - ./config:/app/config:rw
    environment:
      - SEARXNG_BASE_URL=http://open-webui-searxng-1:8080/
    depends_on:
      searxng:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      retries: 3
      start_period: 10s

networks:
  searxng_network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
