# Use default settings as a base
use_default_settings: true

server:
  secret_key: "mysecurekey123"  # ✅ This must be a string!
  limiter: false  # ✅ Disabled rate limiting
  image_proxy: true
  bind_address: "0.0.0.0"  # ✅ Ensures Open WebUI can access SearXNG
  port: 8080  # ✅ Matches the container port in Docker
  default_format: json  # ✅ Forces JSON output for API
  enable_http_api: true  # ✅ Enables API for Open WebUI
  public_instance: true  # ✅ Prevents `403 FORBIDDEN` by allowing external queries
  allow_all_engines: true  # ✅ Allows queries from all engines

ui:
  static_use_hash: true

redis:
  url: redis://searxng-redis:6379/0  # ✅ Corrected Redis URL

search:
  formats:
    - html
    - json  # ✅ Enables JSON output for Open WebUI
  autocomplete: "duckduckgo"
  safe_search: 0  # 0 = Disable Safe Search, 1 = Moderate, 2 = Strict

request_timeout: 10.0  # ✅ Prevent connection failures

engines:
  - name: duckduckgo
    shortcut: ddg
    enabled: true
  - name: brave
    shortcut: br
    enabled: true
  - name: wikipedia
    shortcut: wiki
    enabled: true
  - name: wikidata
    shortcut: wd
    enabled: true
  - name: google
    shortcut: g
    enabled: true  # ✅ Added Google Search (if API is configured)

corsdomains:
  - "http://localhost:3000"
  - "http://127.0.0.1:3000"
  - "*"

headers:
  Access-Control-Allow-Origin: "*"
  Access-Control-Allow-Methods: "GET, POST, OPTIONS"
  Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With, User-Agent, Referer, Origin"
  Access-Control-Allow-Credentials: "true"  # ✅ Fixes browser requests

botdetection:
  use_default_bots_detection: false
  protection_enabled: false
  trust_x_forwarded_for: true

logging:
  level: DEBUG
  log_queries: true
  log_search_errors: true
